name: Deploy Frontend to S3 (+ CloudFront)

on:
  push:
    branches: [main] # deploy on pushes to main
  workflow_dispatch: {} # allow manual runs

permissions:
  id-token: write # required for OIDC
  contents: read

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: "npm"

      - name: Install & Build
        run: |
          npm ci
          npm run build
          # If your build output is not "dist", change the sync folder below.

      - name: Configure AWS credentials (OIDC)
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.AWS_ROLE_TO_ASSUME }}
          aws-region: ${{ vars.AWS_REGION }}

      - name: Upload to S3
        run: |
          aws s3 sync dist s3://${{ vars.S3_BUCKET }} --delete

      - name: Invalidate CloudFront (if configured)
        if: ${{ vars.CF_DIST_ID && vars.CF_DIST_ID != '' }}
        run: |
          aws cloudfront create-invalidation \
            --distribution-id ${{ vars.CF_DIST_ID }} \
            --paths "/*"
